import { Product } from './types';

export const products: Product[] = [
  // {
  //   id: "suit-grey-check-3p",
  //   name: "کت‌ و شلوار سه تکه چهارخانه",
  //   price: 16800000,
  //   currency: "Toman",
  //   image: "https://picsum.photos/400/600?random=1",
  //   images: ["https://picsum.photos/400/600?random=1", "https://picsum.photos/400/600?random=101", "https://picsum.photos/400/600?random=201"],
  //   short: "پارچه پشم مرینو چهارخانه",
  //   description: "کت‌ و شلوار سه تکه چهارخانه با بافت ظریف و رنگ ذغالی، انتخابی بی‌نظیر برای جلسات کاری مهم و مراسم رسمی. دوخت اسلیم‌فیت و جلیقه کلاسیک، استایلی مقتدر و جذاب می‌سازد.",
  //   category: "suits",
  //   fabric: "پشم",
  //   stock: 5
  // },
  // {
  //   id: "suit-navy-royal",
  //   name: "کت‌ و شلوار سرمه‌ای رویال",
  //   price: 15500000,
  //   currency: "Toman",
  //   image: "https://picsum.photos/400/600?random=2",
  //   images: ["https://picsum.photos/400/600?random=2", "https://picsum.photos/400/600?random=102"],
  //   short: "سرمه‌ای کلاسیک",
  //   description: "کت‌ و شلوار سرمه‌ای رویال، نماد قدرت و اعتماد به نفس. با برش مدرن و پارچه ضدچروک، مناسب استفاده روزمره مدیران و رویدادهای شبانه. به همراه کراوات قرمز برای تضاد رنگی جذاب.",
  //   category: "suits",
  //   fabric: "پشم و ابریشم",
  //   stock: 8
  // },
  // {
  //   id: "suit-brown-vintage",
  //   name: "کت‌ و شلوار قهوه‌ای وینتیج",
  //   price: 17200000,
  //   currency: "Toman",
  //   image: "https://picsum.photos/400/600?random=3",
  //   images: ["https://picsum.photos/400/600?random=3"],
  //   short: "سه تکه قهوه‌ای سوخته",
  //   description: "این ست سه تکه با رنگ قهوه‌ای خاص و بافت غنی، استایلی متفاوت و گرم برای فصول سرد سال ارائه می‌دهد. مناسب آقایانی که به دنبال تمایز و وقار کلاسیک هستند.",
  //   category: "suits",
  //   fabric: "پشم فلانل",
  //   stock: 3
  // },
  // {
  //   id: "suit-grey-formal",
  //   name: "کت‌ و شلوار طوسی رسمی",
  //   price: 16500000,
  //   currency: "Toman",
  //   image: "https://picsum.photos/400/600?random=4",
  //   images: ["https://picsum.photos/400/600?random=4"],
  //   short: "طوسی مات سه تکه",
  //   description: "کت و شلوار ذغالی مات با طراحی مینیمال و برش دقیق. به همراه جلیقه هم‌رنگ و کراوات مشکی طرح‌دار، گزینه‌ای همیشگی و شیک برای محیط‌های اداری و قرارهای رسمی.",
  //   category: "suits",
  //   fabric: "پشم",
  //   stock: 12
  // },
  // {
  //   id: "suit-burgundy-sig",
  //   name: "کت‌ و شلوار زرشکی سیگنیچر",
  //   price: 18000000,
  //   currency: "Toman",
  //   image: "https://picsum.photos/400/600?random=5",
  //   images: ["https://picsum.photos/400/600?random=5"],
  //   short: "زرشکی مجلسی",
  //   description: "رنگ زرشکی عمیق این کت‌وشلوار سه تکه، آن را به گزینه‌ای ایده‌آل برای دامادها و مراسم جشن تبدیل کرده است. ترکیبی از جسارت رنگی و اصالت دوخت.",
  //   category: "suits",
  //   fabric: "ابریشم و پشم",
  //   stock: 2
  // },
  // {
  //   id: "suit-light-grey-summer",
  //   name: "کت‌ و شلوار طوسی روشن",
  //   price: 14900000,
  //   currency: "Toman",
  //   image: "https://picsum.photos/400/600?random=6",
  //   images: ["https://picsum.photos/400/600?random=6"],
  //   short: "طوسی روشن با کراوات قهوه‌ای",
  //   description: "رنگ طوسی روشن و پارچه سبک این مدل، آن را برای مراسم روز و فصول گرم سال مناسب می‌سازد. ترکیب آن با اکسسوری‌های قهوه‌ای، استایلی فرش و جوان‌پسند می‌سازد.",
  //   category: "suits",
  //   fabric: "کتان و پشم",
  //   stock: 10
  // },
  // {
  //   id: "accessory-brooch",
  //   name: "بج سینه رسمی دست‌ساز",
  //   price: 650000,
  //   currency: "Toman",
  //   image: "https://picsum.photos/400/600?random=30",
  //   images: ["https://picsum.photos/400/600?random=30"],
  //   short: "بج دست‌ساز لوکس",
  //   description: "بج سینه رسمی با طراحی کلاسیک و ساخت دست‌ساز، تکمیل‌کننده‌ ظاهری شیک و مجلسی برای پیراهن و کت‌وشلوار مردانه است.",
  //   category: "accessories",
  //   stock: 50
  // },
  // {
  //   id: "shirt-luxury-s6",
  //   name: "پیراهن لاکچری مردانه",
  //   price: 4200000,
  //   currency: "Toman",
  //   image: "https://picsum.photos/400/600?random=10",
  //   images: ["https://picsum.photos/400/600?random=10"],
  //   short: "پیراهن با بافت خاص پریمیوم",
  //   description: "پیراهن لاکچری مردانه تهیه‌شده از بهترین الیاف با طراحی انحصاری، مناسب برای استایل‌های رسمی و مجلسی. بافت خاص این پیراهن، جلوه‌ای اصیل و فاخر به پوشش شما می‌بخشد.",
  //   category: "shirts",
  //   stock: 15
  // },
  // {
  //   id: "blazer-premium-b2",
  //   name: "کت پریمیوم درز تک",
  //   price: 14800000,
  //   currency: "Toman",
  //   image: "https://picsum.photos/400/600?random=20",
  //   images: ["https://picsum.photos/400/600?random=20"],
  //   short: "کت پریمیوم کلاسیک مردانه",
  //   description: "کت پریمیوم درز تک با دوختی دقیق و پارچه‌ای باکیفیت، انتخابی لوکس برای مردانی است که در رویدادهای رسمی و مهم به دنبال ظاهری شیک، موقر و حرفه‌ای هستند.",
  //   category: "blazers",
  //   stock: 7
  // },
  // {
  //   id: "accessory-tie-premium",
  //   name: "کراوات ابریشمی فاخر مردانه",
  //   price: 1800000,
  //   currency: "Toman",
  //   image: "https://picsum.photos/400/600?random=31",
  //   images: ["https://picsum.photos/400/600?random=31"],
  //   short: "کراوات ابریشمی لوکس",
  //   description: "کراوات ابریشمی فاخر با بافتی باکیفیت و رنگ‌های جذاب، مناسب برای استایل رسمی و ظاهری شیک و حرفه‌ای.",
  //   category: "accessories",
  //   stock: 25
  // },
  // {
  //   id: "blazer-ms63",
  //   name: "کت رسمی MS-63",
  //   price: 17500000,
  //   currency: "Toman",
  //   image: "https://picsum.photos/400/600?random=21",
  //   images: ["https://picsum.photos/400/600?random=21"],
  //   short: "دوخت سفارشی ممتاز",
  //   description: "کت رسمی MS-63 با دوخت سفارشی و پارچه ممتاز، انتخابی لوکس برای افرادی است که به دنبال تلفیق زیبایی سنتی و طراحی مدرن هستند. مناسب استفاده در مراسم و محیط‌های کاری سطح‌بالا.",
  //   category: "blazers",
  //   stock: 4
  // },
  // {
  //   id: "shirt-classic-s0",
  //   name: "پیراهن کلاسیک سفید مردانه",
  //   price: 2850000,
  //   currency: "Toman",
  //   image: "https://picsum.photos/400/600?random=11",
  //   images: ["https://picsum.photos/400/600?random=11"],
  //   short: "پیراهن سفید رسمی",
  //   description: "پیراهن کلاسیک سفید با بافت ریز و پارچه‌ای درجه‌یک، مناسب برای انواع کت و شلوار رسمی. این مدل همواره انتخابی مطمئن، حرفه‌ای و شیک برای استایل مردانه است.",
  //   category: "shirts",
  //   stock: 20
  // },
  // {
  //   id: "shirt-navy-s1",
  //   name: "پیراهن سرمه‌ای مردانه",
  //   price: 3100000,
  //   currency: "Toman",
  //   image: "https://picsum.photos/400/600?random=12",
  //   images: ["https://picsum.photos/400/600?random=12"],
  //   short: "پیراهن ابریشمی مخلوط",
  //   description: "پیراهن سرمه‌ای با طراحی معاصر و بافتی باکیفیت، مناسب استایل رسمی، جلسات مهم و مراسم مجلسی. این رنگ همیشه ظاهری جدی، شیک و قدرتمند ایجاد می‌کند.",
  //   category: "shirts",
  //   stock: 18
  // },
  // {
  //   id: "accessory-pocketquare",
  //   name: "دستمال جیب رسمی ابریشمی",
  //   price: 450000,
  //   currency: "Toman",
  //   image: "https://picsum.photos/400/600?random=32",
  //   images: ["https://picsum.photos/400/600?random=32"],
  //   short: "دستمال جیبی ابریشمی",
  //   description: "دستمال جیب رسمی با پارچه ابریشمی و نقوش ظریف، یک اکسسوری شیک برای تکمیل استایل رسمی و افزودن جذابیت بصری به کت‌وشلوار است.",
  //   category: "accessories",
  //   stock: 40
  // }
];