# Generated by Django 5.2.9 on 2025-12-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_contactmessage_product_sitesettings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='accessories_section_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='bespoke_section_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='blazers_section_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='shirts_section_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='suits_section_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
    ]
