# Generated by Django 5.2.16 on 2026-10-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_authsession"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThrottleBucket",
            fields=[
                (
                    "key",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("count", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
        ),
    ]
